### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by victor-moreno** [odegeasslbc/Progressive-GAN-pytorch#2]
Hi,
Your code looks very clean, so I tried to test it but got this error:
Using pytorch 1.6.0

python train.py --path data --trial pgan

[ some warnings deleted (about add_ and interpolate) ]

Traceback (most recent call last):
  File "train.py", line 246, in <module>
    train(generator, discriminator, args.init_step, loader, args.total_iter)
  File "train.py", line 124, in train
    real_predict.backward(mone)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 121, in backward
    grad_tensors = _make_grads(tensors, grad_tensors)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 34, in _make_grads
    + str(out.shape) + ".")
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([])

**Comment by victor-moreno** [comment]
I found the fix. It is related to a new version or torch that supports zero length tensors.
Tensor one in train.py line 87 should be created as:

    one = torch.tensor(1, dtype=torch.float).to(device)
